name: "install with"

on:
  push:
    branches: ["~MAIN_BRANCH~"]
  pull_request:
    branches: ["~MAIN_BRANCH~"]

env:
  PRIMARY: "~PRIMARY~"
  #PERL_USE_UNSAFE_INC: 0
  AUTHOR_TESTING: 0
  AUTOMATED_TESTING: 1
  RELEASE_TESTING: 0

jobs:
  # ---------------------------------------------------------
  # testing module installation using cnext
  # ---------------------------------------------------------
  cnext:
    runs-on: ubuntu-latest
    steps:
      - run: perl -V
      - uses: perl-actions/install-with-cnext@cnext-ci
      - run: perl -M${{ env.PRIMARY }} -e1

  # ---------------------------------------------------------
  # testing module installation using cpm
  # ---------------------------------------------------------
  cpm:
    runs-on: ubuntu-latest
    steps:
      - run: perl -V
      - uses: perl-actions/install-cpm@cnext-ci
        with:
          install: "${{ env.PRIMARY }}"
      - run: perl -M${{ env.PRIMARY }} -e1

  # ---------------------------------------------------------
  # testing module installation using cpanm
  # ---------------------------------------------------------
  cpanm:
    runs-on: ubuntu-latest
    steps:
      - run: perl -V
      - uses: perl-actions/install-cpanm@cnext-ci
        with:
          install: ${{ env.PRIMARY }}
      - run: perl -M${{ env.PRIMARY }} -e1
